[package]
name = "spooks"
version = "0.1.0"
edition = "2024"

[lib]
name = "spooks"
crate-type = ["cdylib"]

[dependencies.windows]
version = "0.*"
features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
]
